gText_Birch_Welcome::
	.string ".\p"
	.string "..\p"
	.string "...\p"
	.string "A human? What are you doing here?\p"
	.string "..."
	.string "You don't know why you are here\n"
	.string "either?\l"
	.string "How mysterious..."
	.string "$"

gText_Birch_Pokemon::
	.string "ERROR: gTextBirchPokemon USED”\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "You don't seem to be here\n"
	.string "physically. Are you sure\n"
	.string "you are not a POKéMON?\p"
	.string "...\p"
	.string "Well, no matter.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "ERROR: gText_Birch_AndYouAre USED”\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "What's your name, child?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}... Hmm...\l"
	.string "I will remember this.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "While I don't know how you\n"
    .string "appeared here, I am sure we\p"
    .string "are fated to meet again\n"
    .string "in the future.\p"
    .string "Until then, {PLAYER}{KUN}.\l"
	.string "$"
